import { Metadata } from 'next'
import ToolPage from '@/components/landing/ToolPage'

export const metadata: Metadata = {
  title: 'AI Voiceover Generator — Text to Speech for Videos',
  description: 'Generate realistic AI voiceovers for your videos in seconds. 35+ voices, multiple accents, and professional audio quality. No recording needed.',
}

export default function Page() {
  return (
    <ToolPage
      badge="AI Voiceover"
      title="Studio-quality voiceovers,"
      titleHighlight="generated by AI"
      description="Turn any script into a professional voiceover in seconds. Choose from 35+ AI voices with natural intonation — no microphone or recording studio required."
      ctaLabel="Try AI Voiceover free"
      ctaHref="/dashboard/tools/voiceover"
      features={[
        { icon: '🎙️', title: '35+ AI Voices', desc: 'Male, female, multiple accents and styles — from calm narrators to energetic presenters.' },
        { icon: '⚡', title: 'Generate in Seconds', desc: 'Paste your script and get a downloadable audio file in under 10 seconds.' },
        { icon: '🎵', title: 'Natural Intonation', desc: 'Advanced TTS models that sound human, not robotic — perfect for TikTok and Reels.' },
        { icon: '📱', title: 'Ready for Any Platform', desc: 'Export MP3 audio optimized for TikTok, YouTube Shorts, Instagram Reels, and more.' },
      ]}
    />
  )
}
